# This is a basic workflow to help you get started with Actions

name: Android CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  APK_FILE_PATH: android/app/build/outputs/apk/release
  APK_FILE_NAME: app-release.apk

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: set up NDK
      uses: ravinderjangra/android-ndk-toolchain-setup@0.2
      with:
        api: '21'
        arch: 'arm'
        install-location: 'toolchains'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
 

    # - uses: actions/checkout@v1
    #   id: cache
    #   with:
    #     path: ~/local/rubies
    #     key: ruby-2.6.5
    #     clean: false
        
    # - name: install fir.im
    #   run: sudo gem install fir-cli
    # - name: Upload to Fir.im
    #   run: fir login ${{ secrets.FIRTOKEN }}
    # - run: fir publish  app/build/outputs/apk/release/app-release.apk
    - name: Upload apk to Pgyer
      run: curl -F 'file=@${{env.APK_FILE_PATH}}/${{env.APK_FILE_NAME}}' -F '_api_key=${{secrets.PGYER_API_KEY}}' https://www.pgyer.com/apiv2/app/upload
