name: Android Release Build
on:
  workflow_dispatch:
    inputs:
      # buildBranch:
      #   description: 'Input which branch to build (develop/main/hotfix)'
      #   required: true
      #   default: 'main'
      buildVersionOrTag:
        description: 'Specify version only when you want to increment the minor and major version (e.g. 1.0.0)'
        required: true
        default: '1.0.0'
      # uploadArtifact:
      #   description: 'Upload apk to Github Artifact (true/false)'
      #   required: false
      #   default: 'false'
      uploadCloud:
        description: 'Upload apk to Pgyer (true/false)'
        required: true
        default: 'true'

jobs:
  build-android-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Prepear variable for build
        id: variable
        env:
          NUM: ${{ github.run_number }}
        run: |
          echo "::set-output name=code::$(($NUM + 10000))"
          echo "::set-output name=date::$(date +'%Y-%m-%dT%H:%M')"
          if [ ! -f CHANGELOG.md];then
            touch CHANGELOG.md
          fi

      - name: Check lint with gradle
        run: |
          chmod +x gradlew & ./gradlew lint

      - name: Update gradle version for Android
        uses: damienaicheh/update-android-version-gradle-action@v1.0.0
        with:
          build-gradle-path: '${{ github.workspace }}/app/build.gradle'
          version-code: ${{ steps.variable.outputs.code }}
          version-name: ${{ github.event.inputs.buildVersionOrTag }}
          print-file: true

      - name: Build with gradle
        run: |
          ./gradlew assembleRelease

      - name: Push to pgyer
        id: pushToPgyer
        run: |
          curl -F 'file=@${{ github.workspace }}/app/build/outputs/apk/release/app-release-unsigned.apk' -F '_api_key=${{secrets.PGYER_API_KEY}}' https://www.pgyer.com/apiv2/app/upload
        continue-on-error: true

      - name: On sucess to send notification
        if: success()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${{ github.event.repository.name }} build success: \"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Type:* Android Version:${{ github.event.inputs.buildVersionOrTag }}(${{ steps.variable.outputs.code }})\"},{\"type\":\"mrkdwn\",\"text\":\"*When:* ${{ steps.variable.outputs.date }} \"}]}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: On failure to send notification
        if: failure()
        uses: slackapi/slack-github-action@v1.16.0
        with:
          payload: "{\"blocks\":[{\"type\":\"section\",\"text\":{\"type\":\"mrkdwn\",\"text\":\"${{ github.event.repository.name }} build failure: \"}},{\"type\":\"section\",\"fields\":[{\"type\":\"mrkdwn\",\"text\":\"*Type:* Android Version:${{ github.event.inputs.buildVersionOrTag }}(${{ steps.variable.outputs.code }})\"},{\"type\":\"mrkdwn\",\"text\":\"*When:* ${{ steps.variable.outputs.date }} \"}]}]}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

      - name: Create tag version
        id: tag
        uses: mathieudutour/github-tag-action@v5.6
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ github.event.inputs.buildTag }}
          dry_run: true
      
      - name: Generate a changelog
        uses: orhun/git-cliff-action@v1
        with:
          config: .github/cliff.toml
          args: --unreleased --tag ${{ steps.tag.outputs.new_tag }} --prepend CHANGELOG.md
        env:
          OUTPUT: CHANGELOG.md 

      - uses: EndBug/add-and-commit@v7
        with:
          message: "ci: update changelog to ${{ github.event.inputs.buildVersionOrTag }}-beta"
          default_author: github_actions
          add: '.github/release-last-commit.txt CHANGELOG.md'